### ISSUE TITLE
setting variables

### ISSUE THREAD

**Issue by ralyodio** [RandomEtc/ejs-locals#14]
This is causing page not to be rendered, data is not found:

login.ejs
<% layout(layout) %>
<% var title = 'Login page' %>

layout.ejs
&lt;title&gt;<%= title %>&lt;/title&gt;

It works fine if I remove the 'var' in the partial.

**Comment by RandomEtc** [comment]
You can do this in login.ejs:

```
<% block('title', "Login page") %>
```

And in layout.ejs:

```
<title><%= blocks.title %></title>
```

**Comment by ralyodio** [comment]
Is there any advantage over just doing:

<% title = 'Login page' %> in the login.ejs

and then <%= title %> in the layout.ejs

It seems to work this way, but as soon as I introduced var, it broke everything.

**Comment by RandomEtc** [comment]
Honestly I don't know, I'm surprised that works at all. I think that it's
creating a global variable. With luck the global only exists in the context
of the template!

**Comment by ralyodio** [comment]
thanks, i'll use the block() just to be safe.

**Comment by ralyodio** [comment]
One more issue, can I use a filter with a block? 

https://github.com/visionmedia/ejs/issues/73

**Comment by RandomEtc** [comment]
If you apply the filter when using the block content it should work fine.

**Comment by RandomEtc** [comment]
Something like `<title><%=: blocks.title | capitalize %></title>` should do it. I confess that I didn't test filters when I wrote this stuff but I have tested them since and they seem to work OK.

**Comment by ralyodio** [comment]
I can't do it like that -- I only have one place where the title uses a filter.
