### ISSUE TITLE
best way to toggle pieces of UI

### ISSUE THREAD

**Issue by ralyodio** [RandomEtc/ejs-locals#15]
I want to toggle a block of html in layout.ejs when called from page.ejs

something like setting hide_title = true; and having layout.ejs look for that variable.

**Comment by RandomEtc** [comment]
Right now I would just set the block to an empty string:

```
<% block('title', '') %>
```

And then in the layout do:

```
<% if (title) { %>
  <h1><%=title%></h1>
<% } %>
```

Hope that helps / sorry for the delay.
