### ISSUE TITLE
THANK YOU, YOU MADE MY LIFE LIVABLE.

### ISSUE THREAD

**Issue by DTrejo** [RandomEtc/ejs-locals#2]
the express 2.x to 3.x transition was hell b/c it took me a while to realize that layout.ejs would never work without your work.
Cheers,
D

PS Thanks to you, wtfjs.org will now run on node 0.6.19, and posting will resume!

**Comment by RandomEtc** [comment]
Oh cool - glad it was useful. I'm still working with it and it's going OK. If you stick with the layout stuff everything should be good. I got a bit carried away with the blocks stuff though - caveat templator :)

If you haven't seen it already, check out SWIG too, it's the most fully featured looking lib I've found so far. Not yet using it in production but my experiments with it are promising.

**Comment by RandomEtc** [comment]
http://paularmstrong.github.com/swig/ is the swig I mean.
