### ISSUE TITLE
pass a variable to layout

### ISSUE THREAD

**Issue by ralyodio** [RandomEtc/ejs-locals#21]
Is it possible to pass a variable to a layout from withing a page.ejs file?

I am doing this now, but it is a global variable I believe:

item.ejs

```
<% pg = 'item'; %>
<% layout('../layout') -%>
```

layout.ejs

```
    <section class="<%= pg ? pg : '' %>">

```

**Comment by RandomEtc** [comment]
There's some discussion of this in #14 - right now you should use blocks to do this. You can also pass the variable in when you call `res.render`.

Consider just having two layouts and/or using includes for the common parts?
