### ISSUE TITLE
Render without expressjs

### ISSUE THREAD

**Issue by olivercox** [RandomEtc/ejs-locals#32]
I'm trying to work out how I can render a view without express. I can get this to work with ejs directly using the ejs.render() method but can't see how I can do this using ejs-locals.

Any pointers would be greatly appreciated.

Many Thanks

Oliver

**Comment by RandomEtc** [comment]
I assume it's crashing because the ejs-locals code is looking for `options.settings`. You might be able to pass an empty object `{ settings: {} }` to overcome that?

Otherwise, please post the errors you're seeing and we can take a closer look.

**Comment by olivercox** [comment]
More fundamental an issue than that but only because I'm I bit dim sometimes. Once I stopped trying to call ejs.renderFile and just called ejs() I did indeed need to set { settings: {} }.

Thanks for help. Now I can generate emails from templates with all the power of ejs-locals...sweet!

**Comment by ixisio** [comment]
I've created something similar https://github.com/ixisio/grunt-ejs-locals
