### ISSUE TITLE
Strange behavior of include

### ISSUE THREAD

**Issue by dmitry-solomadin** [RandomEtc/ejs-locals#9]
When I use inside of template like this: 

``` javascript
include('shared/scripts')
```

and then inside the same template call:

``` javascript
include('someTemplate')
```

I get error message saying that it cannot find someTemplate inside shared folder.

This is strange that it is trying to lookup relative to previous include.

**Comment by RandomEtc** [comment]
Can you post a fuller example and help me understand how this differs from #10? Thanks!

**Comment by RandomEtc** [comment]
I have added some tests in `v0.2.1` for `include()` to test calling multiple times and using relative paths to find templates. I wasn't able to recreate the error. Closing this but please re-open if it's still a problem.
